name: Buill NixOS Configurations
on: [push]

jobs:
  Build-NixOS-Configurations:
    runs-on: nix-builder
    strategy:
      matrix:
        system:
          - "carbon"
          - "git"
          - "gospel"
          - "node"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo 'Building configuration for ${{ matrix.system }}'
          nix build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
