name: Buill NixOS Configurations
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:25
      volumes:
        - "/nix:/nix"
    strategy:
      matrix:
        system:
          - "carbon"
          - "git"
          - "gospel"
          - "node"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo 'Building configuration for ${{ matrix.system }}'
          nix build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
      - name: Push build to attic
        run: |
          nix run nixpkgs#attic-client -- login gospel https://attic.kilonull.com ${{ secrets.ATTIC_PUSH_SECRET }}
          nix run nixpkgs#attic-client -- push gospel:nixosConfigs ./result
