name: Forgejo Actions Demo
run-name: ${{ forgejo.actor }} is testing out Forgejo Actions 🚀
on: [push]

jobs:
  Explore-Forgejo-Actions:
    runs-on: docker
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ forgejo.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Forgejo!"
      - run: echo "🔎 The name of your branch is ${{ forgejo.ref }} and your repository is ${{ forgejo.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ forgejo.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ forgejo.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
